name: Install Zoo CLI
description: "Install Zoo CLI on a Linux or Windows host for use in GitHub workflows"
inputs: {}
outputs:
  version:
    description: "The Zoo CLI version that was installed"
runs:
  using: "node20"
  main: "index.js"
